### ISSUE TITLE
Install failed while aptitude is not installed under Ubuntu 14.04.

### ISSUE THREAD

**Issue by ppoffice** [Andrewpk/Microsoft--SQL-Server--ODBC-Driver-1.0-for-Linux-Fixed-Install-Scripts#10]
I changed `aptitude` to `apt` and the installation went well. I think `aptitude` should be mentioned as a dependency or add `apt` detection to the script.

**Comment by Andrewpk** [comment]
i'll just switch it to using apt. thanks for bringing this up!
