### ISSUE TITLE
error checking for x86_64

### ISSUE THREAD

**Issue by nakchak** [Andrewpk/Microsoft--SQL-Server--ODBC-Driver-1.0-for-Linux-Fixed-Install-Scripts#3]
Just spun up a fresh debian vm under hyper-v ( uname -a
Linux vs-kam-dev01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux)

when uname -p is run it returns "unknown" causing the script to error out, however uname -m returns the correct string or x86_64.  Maybe add a guard clause to line 74 of build_dm.sh incase uname -p returns unknown and it checks the machine hardware name instead of the processor when used in a visualized environment?, my local modification to line 74 to just check uname -m allows the script to run successfully.

**Comment by Andrewpk** [comment]
Thanks for the heads up!
