### ISSUE TITLE
Check needed that en_US.UTF-8 is installed on machine

### ISSUE THREAD

**Issue by nakchak** [Andrewpk/Microsoft--SQL-Server--ODBC-Driver-1.0-for-Linux-Fixed-Install-Scripts#4]
Just ran the scripts but sql cmd was presenting me with the following: 
` sqlcmd
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted`

After a bit of googling found that en_US.UTF8 was a dependancy for it to run.

A simple check would be to check for the presence of the string "en_US.utf8" in the output of `locale -a`

**Comment by Andrewpk** [comment]
I did not know that. Will add tonight unless anyone submits a PR first :dancer:

**Comment by nakchak** [comment]
I would submit a PR other than my shell scripting skills are somewhat lacking, just good at breaking things and working out why ;)

**Comment by hktalent** [comment]
@Andrewpk @nakchak me too, in kali linux
#3 and #4 
not fixes,thanks
```
cat /etc/apt/sources.list
deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb  https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017 xenial main


sudo apt-get update 
sudo apt-get install mssql-tools


./bin/sqlcmd -?
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

locale -a
C
C.UTF-8
POSIX
```

**Comment by hktalent** [comment]
@Andrewpk @nakchak me too, in kali linux
```
vi /etc/locale.gen
en_US.UTF-8 UTF-8


sudo locale-gen
```

so is ok
fixed
