### ISSUE TITLE
Add a list of OS's to check for

### ISSUE THREAD

**Issue by singlecheeze** [Andrewpk/Microsoft--SQL-Server--ODBC-Driver-1.0-for-Linux-Fixed-Install-Scripts#6]
Andrew,

Thanks for posting on my blog! One issue I ran into in your install.sh was when I was trying to install on my Linux Mint dev machine. The install kept breaking on trying to find the correct dependencies for a Debian system as the initial If statement was skipped and it was thinking my box was Red Hat or CentOS. 

After a little digging I simply edited your script here:
if [ $os_dist_id == "LinuxMint" ] || [ $os_dist_id == "Debian" ]; then
    req_libs=( '~i"^libc6$"' '~i"libkrb5\-[0-9]$"' '~i"^e2fsprogs$"' '~i"^openssl$"' )
else
    req_libs=( glibc e2fsprogs krb5-libs openssl )
fi

Could you give the bash a variable that is a list so it could easily be appended to, or a command line argument to specify a distro if not Ubuntu or Debian?

Just food for thought ;)

Thanks again for saving me a ton of time!

Dave

**Comment by Andrewpk** [comment]
Hello!

I added new install flags --force-debian and --force-redhat to force the req_libs variable to be changed. Linux Mint is a pretty popular distro so I just added that to the checked list as well as checking for /etc/debian_version.

-Andrew
