### ISSUE TITLE
variable substitution error in install.sh

### ISSUE THREAD

**Issue by swiftsword** [Andrewpk/Microsoft--SQL-Server--ODBC-Driver-1.0-for-Linux-Fixed-Install-Scripts#7]
Andrew, great work - this helped me a lot. I noticed the following in install.sh, line 26:

if [ $os_dist_id == "Ubuntu" ] || [ $os_dist_id == "Debian" ] || [ $os_dist_id == "LinuxMint" ] || [ -e "$is_this_debian_based" ]; then
    req_libs=deb_req_libs  <-----should be $deb_req_libs
else
    req_libs=red_req_libs  <-----should be $deb_req_libs
fi 

Cheers,

Oliver

**Comment by Andrewpk** [comment]
I'm going to start tagging commits with a release number so that changes can be made, verified, and then tagged once verified working so that we don't run into situations like this anymore. Sorry about this.

**Comment by Andrewpk** [comment]
I had an error when copying arrays so I fixed that. Newest build_dm and install should work
