### ISSUE TITLE
Problem on Debian 8.x

### ISSUE THREAD

**Issue by joakimlemb** [Andrewpk/Microsoft--SQL-Server--ODBC-Driver-1.0-for-Linux-Fixed-Install-Scripts#8]
build_dm.sh:
uname -p does not work on debian 8.x for some reason.
Solved by changing to uname -m

patch: http://pastebin.com/kddDiyEw

install.sh:
Multiple problems with debian 8.x, got it working with some tweaks.

patch: http://pastebin.com/PjBJ1dzb <- ignore this one, multiple errors thanks to some uncareful sed commands.

more correct patch for install.sh: http://pastebin.com/H0xa6Jy7

edit: patches moved to pastebin

**Comment by Andrewpk** [comment]
I'll merge those changes in and modify the existing `debian` checks and rename the checks to `ubuntu` since they're quite ubuntu derivative specific.

**Comment by Andrewpk** [comment]
Added some of your requests in the latests commits

**Comment by joakimlemb** [comment]
Thanks.
